
openapi: 3.0.1
info:
  title: InsurTech Sandbox
  version: 1.0.0
paths:
  /home:
    get:
      description: Get information about a home
      tags:
        - Home Insurance
      responses:
        '200':
          description: Get a Home
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Home'
    post:
      description: Create a new home
      tags:
        - Home Insurance
      responses:
        '200':
          description: Create a Home
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Home'
  /claim:
    get: 
      description: Get information about a claim
      tags:
        - "Home Insurance"
      responses:
        '200':
          description: Get a Claim
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
    post:
      description: Create a new claim
      tags:
        - Home Insurance
      responses:
        '200':
          description: Create a Claim
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
components:
  schemas:
    Home:
      type: object
      properties:
        id:
          type: integer
          format: int64
        location:
          type: number
          format: string
        city:
          type: number
          format: string
        country:
          type: number
          format: string
        bedrooms:
          type: number
          format: float
        bathrooms:
          type: number
          format: float
    HouseClaim:
      type: object
      properties:
        id:
          type: integer
          format: int64
        home_id:
          type: number
          format: int64
        reason:
          type: number
          format: string